project_id = "yvyrqkckhpxvlcvinsht"

[functions.analizar-guion]
verify_jwt = false

[functions.extract-pdf-text]
verify_jwt = false

[functions.generar-memoria]
verify_jwt = false

[functions.generar-presupuesto]
verify_jwt = false

[functions.ai-generate]
verify_jwt = false
